name: Build Calculator EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest  # ставим Windows, чтобы собрать .exe

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if exist requirements.txt pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller main.py --onefile --noconsole --icon=resources/icon.ico --name=Calculator

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Calculator
        path: dist/Calculator.exe
